### ISSUE TITLE
Update proguard documentation

### ISSUE THREAD

**Issue by NicolaChimerapps** [beworker/tinybus#27]
In the readme, the proguard configuration lists:
```
-keepclassmembers class ** {
    @de.halfbit.tinybus.Subscribe public *;
    @de.halfbit.tinybus.Produce public *;
}
```
Should it not be 'com' instead of 'de':
```
-keepclassmembers class ** {
    @com.halfbit.tinybus.Subscribe public *;
    @com.halfbit.tinybus.Produce public *;
}
```

**Comment by beworker** [comment]
Please pull the latest changes. Readme is up-to-date.

**Comment by beworker** [comment]
Sorry. I misread the first message. Here is update. I changed the package in Version 3 to make it more consistent with Maven artifacts. Readme already describes the changes in v3. I will make it more clear in Readme file in a minute.
