### ISSUE TITLE
@Subscribe visibility?

### ISSUE THREAD

**Issue by nono240** [beworker/tinybus#31]
It would be nice to be able to use private/protected/package methods as @Subscribe... Public methods are pollutions.

**Comment by beworker** [comment]
This was an explicit design decision. The reason for that is that future versions of TinyBus may use generated code instead of runtime reflection. Keeping methods public will give more flexibility if case of such changes in the future.

**Comment by nono240** [comment]
Make sense. Would be nice to generate a warning though ;)

**Comment by beworker** [comment]
You mean when a method is private of protected?

**Comment by nono240** [comment]
Yes.

**Comment by beworker** [comment]
Agree. That what I was thinking about. I didn't want to introduce these checks at runtime. But it's a good idea to have them at compile time. Just created a separate TODO for it.
