### ISSUE TITLE
Generate warnings for not public handler methods

### ISSUE THREAD

**Issue by beworker** [beworker/tinybus#32]
When @Subscribe or @Produce are applied to not public methods, then TinyBus must fail fast.

**Comment by beworker** [comment]
When @Subscribe or @Produce are applied to not public methods, then TinyBus must fail fast.

**Comment by pundegreen** [comment]
Just spent 2 hours trying to figure out what's wrong, turned out my methods weren't public. :+1: to resolve this issue!

**Comment by tobrun** [comment]
> Just spent 2 hours trying to figure out what's wrong
Been there done that multiple times, +1 for this to be implemented

**Comment by beworker** [comment]
@tobrun @pundegreen 
Scanning though all methods takes a bit longer. To keep same performance I would like to perform this check when BuildConfig.DEBUG equals true. How do you think guys, would it be enough for you?

**Comment by pundegreen** [comment]
@beworker yes, totally

**Comment by beworker** [comment]
@pundegreen Ok. It's an easy task then. I'll try to finish it next week.

**Comment by sergejsha** [comment]
Closing as outdated.
