### ISSUE TITLE
TinyBus can't deliver large objects?

### ISSUE THREAD

**Issue by droiderman** [beworker/tinybus#36]
Consider the following event class: 

    public final class ParseEvent extends Event {

    private User user;

    public ParseEvent(User user) {
        this.type = Type.ON_USER_PARSE_COMPLETE;
        this.user = user;
    }

    public User user() {
        return user;
    }
    }

Calling post() with an instance of this class does not trigger anything. The `User` object is quite large with a lot of fields, could this be the issue?

**Comment by beworker** [comment]
No. This cannot be because of the size of the object. How does subscriber look like?

**Comment by droiderman** [comment]
So I'm going to elaborate a little. This is the base Event class:

     public class Event {

    public enum Type {
        /* LoginActivity events */
        ON_LOGIN_PRESS, ON_TERMS_PRESS, ON_LOGIN_CANCELLED,
        /* Parser events */
        ON_USER_PARSE_COMPLETE
    }

    protected Type type;

    public Event(Type type) {
        this.type = type;
    }

    /* default constructor */
    public Event() {}

    public Type getType() {
        return type;
    }
   }

The subscriber uses `Activity` context and has an annotated `onEvent()` method.
    
        [at]Subscribe
        public void onEvent(Event event) 

Register/unregister is in `onStart()/onStop()` The strange thing is that `EventBus.getBus().post(new Event(Event.Type.ON_LOGIN_CANCELLED));` works and triggers the method while `EventBus.getBus().post(new ParseEvent(user));` doesn't do anything.

**Comment by beworker** [comment]
Event inheritance is not supported. You have to register subscriber for ParseEvent. Subscriber method registered for base Event will never be called.

**Comment by droiderman** [comment]
good to know, thanks for clarifying this
