### ISSUE TITLE
Only last event gets delivered when posting multiple events via .postDelayed()

### ISSUE THREAD

**Issue by TheKlint** [beworker/tinybus#46]
If I send multiple consecutive events via .postDelayed(), only the last event is delivered to the subscriber. 

Example:
MyEvent eventA = new MyEvent("A");
MyEvent eventB = new MyEvent("B");

mBus.postDelayed(eventA, 1000);
mBus.postDelayed(eventB, 1000);

In the subscriber method I only get 'eventB' delivered.

**Comment by beworker** [comment]
It works as designed (see javadoc postDelayed() method). Typical use case is to debounce events coming very often and deliver only last one. What is your use case when you need multiple delayed events to be delivered?

**Comment by TheKlint** [comment]
Thank you for the quick reply.
I have multiple objects which send out "MyEvent" (delayed) events, and I need them all delivered to the subscribing method.

**Comment by beworker** [comment]
You should rather use standard android.os.Handler for this. As for now tinybus can handle only last event.
