### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by TheKlint** [beworker/tinybus#49]
Hello,

In our app we are seeing this java.lang.RuntimeException once in a while.
Unfortunately, there are nothing in the stack trace which indicates where in our code or when this happens.

**Version:** de.halfbit:tinybus:3.0.2

java.lang.RuntimeException
de.halfbit.tinybus.TinyBus.handleExceptionOnEventDispatch(SourceFile:329)
de.halfbit.tinybus.TinyBus.processQueue(SourceFile:383)
de.halfbit.tinybus.TinyBus$TinyBusImpl.onPostFromBackground(SourceFile:529)
de.halfbit.tinybus.impl.Task.run(SourceFile:87)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:158)
android.app.ActivityThread.main(ActivityThread.java:7229)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.reflect.Method.invoke(Native Method)
de.halfbit.tinybus.TinyBus$TinyBusImpl.dispatchEvent(SourceFile:460)
de.halfbit.tinybus.TinyBus.processQueue(SourceFile:380)
de.halfbit.tinybus.TinyBus$TinyBusImpl.onPostFromBackground(SourceFile:529)
de.halfbit.tinybus.impl.Task.run(SourceFile:87)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:158)
android.app.ActivityThread.main(ActivityThread.java:7229)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by beworker** [comment]
Can it be that one of your `@Subscribe` methods is not public? Could you please check it out?

**Comment by TheKlint** [comment]
All the `@Subscribe` methods are public.
Do you have any other suggestions?

**Comment by beworker** [comment]
I would suggest to prepare a special version of the library with a try-catch block around line 460 of `TinyBus.java`.

```
try {
    subscriberCallback.method.invoke(receiver, event);
} catch (Exception e) {
   Log.e(TAG, 'kaboom -----', e);
   Log.d(TAG, subscriberCallback);
   Log.d(TAG, subscriberCallback.method);
   Log.d(TAG, receiver);
   Log.d(TAG, event);
}
```

This shall give you much better insides on what gets wrong when it fails once again. If you use crashlytics you can post more details to crashlytics. Hope this helps.

**Comment by TheKlint** [comment]
Thanks. We should give that a try.

**Comment by beworker** [comment]
Please keep me updated once you have more details.

**Comment by TheKlint** [comment]
It seems that it was our bug reporting tool, which was not providing enough information to us. The crash does not originate from TinyBus, but from some of our own code.
Closing the issue/question...
